version: '3'
services:
  app:
    image: daniel570/zesty-challenge:latest
    ports:
      - 5050:5050
    depends_on:
      - dynamodb
    env_file:
      - .env

  dynamodb:
    image: zestyco/dynamodb-challenge:amd
    ports:
      - 8000:8000

